params:
    epoch: 400
    learning_rate: 1.0E-4
    patch_x: 256
    patch_y: 256
    kern_size: 3
    n_patches_per_image: 32
    startfilter: 32
    validation_split: 0.0001
    n_channel_in: 3
    pattern: '.tiff'
    depth: 2
    batch_size: 10
    generate_npz: True
    train_unet: True
    train_seed_unet: True
    train_star: False
    RGB: True
    num_channels: 3
files:
  npz_filename : 'Kapoorlabs_NeuroIPS_p256'
  model_name : 'Kapoorlabs_NeuroIPS_p256_d2_f32_r64'
paths:
  model_dir : '/gpfsstore/rech/jsy/uzj81mi/Segmentation_Models/'
  base_dir : '/gpfsscratch/rech/jsy/uzj81mi/Segmentation_challenge/NeurIPS_CellSegData/Train_Labeled/'
  raw_dir : 'raw_patches_512_xl/'
  real_mask_dir : 'real_patch_mask_512_xl/'
  binary_mask_dir : 'binary_patch_mask_512_xl/'
  binary_erode_mask_dir : 'binary_patch_erode_mask_512_xl/'