params:
    epoch: 200
    learning_rate: 1.0E-3
    patch_x: 128
    patch_y: 128
    kern_size: 3
    n_patches_per_image: 32
    n_rays: 64
    startfilter: 32
    validation_split: 0.0001
    n_channel_in: 3
    pattern: '.tiff'
    depth: 3
    batch_size: 10

files:
  npz_filename : 'Kapoorlabs_NeuroIPS_p128'
  model_name : 'Kapoorlabs_NeuroIPS_p128_d3_f32_r64'
paths:
  model_dir : '/gpfsstore/rech/jsy/uzj81mi/Segmentation_Models/'
  base_dir : '/gpfsstore/rech/jsy/uzj81mi/Segmentation_challenge/NeurIPS_CellSegData/Train_Labeled/'
  raw_dir : 'raw/'
  real_mask_dir : 'real_mask/' 
  binary_mask_dir : 'binary_mask/'
  binary_erode_mask_dir : 'binary_erode_mask/'